spring :
  application:
    name: addressBookForChurch
  config :
    import:
      - optional:application-secret.yml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
